version: '3.8'
services:
  analytics:
    container_name: scraper-analytics
    build:
      context: .
      dockerfile: ./apps/analytics/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  queue:
    container_name: scraper-queue
    build:
      context: .
      dockerfile: ./apps/queue/Dockerfile
      target: prod
      args:
        - REPO_TOKEN=${REPO_TOKEN}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env

  worker:
    container_name: scraper-worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: prod
      args:
        - REPO_TOKEN=${REPO_TOKEN}
    environment:
      - NODE_ENV=production
      - QUEUE_SOCKET_URL=ws://queue:3001
    env_file:
      - .env
    depends_on:
      - queue
