
services:
  analytics:
    container_name: scraper-analytics-dev
    build:
      context: .
      dockerfile: ./apps/analytics/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/analytics/.env
    volumes:
      - ./apps/analytics:/app
      - analytics_node_modules:/app/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/analytics
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/analytics/package.json

  worker:
    container_name: scraper-worker-dev
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: dev
      args:
        - REPO_TOKEN=${REPO_TOKEN}
    environment:
      - NODE_ENV=development
      - QUEUE_SOCKET_URL=${QUEUE_SOCKET_URL}
    env_file:
      - .env
    depends_on:
      - queue
    volumes:
      - .:/app
      - worker_node_modules:/app/apps/worker/node_modules
      - ./logs:/app/logs
    working_dir: /app/apps/worker
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/worker/src
          target: /app/apps/worker/src
        - action: sync
          path: ./packages
          target: /app/packages
        - action: rebuild
          path: ./apps/worker/package.json

  queue:
    container_name: scraper-queue-dev
    build:
      context: .
      dockerfile: ./apps/queue/Dockerfile
      target: dev
      args:
        - REPO_TOKEN=${REPO_TOKEN}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./apps/queue:/app
      - queue_node_modules:/app/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/queue/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/queue/package.json
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"  
      - "127.0.0.1:4510-4559:4510-4559" 
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_HOST=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volume:/var/lib/localstack"

volumes:
  analytics_node_modules:
  worker_node_modules:
  queue_node_modules:
  localstack_data:
