version: '3.8'
services:
  analytics:
    container_name: scraper-analytics
    build:
      context: .
      dockerfile: ./analytics/Dockerfile
      target: prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  backend:
    container_name: scraper-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
      args:
        - REPO_TOKEN=${REPO_TOKEN}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
