
services:
  analytics:
    container_name: scraper-analytics-dev
    build:
      context: ./apps/analytics
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/analytics/.env # Add if .env file exists
    volumes:
      - ./apps/analytics:/app
      - analytics_node_modules:/app/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/analytics
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/analytics/package.json

  worker:
    container_name: scraper-worker-dev
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - queue
    volumes:
      - ./apps/worker/src:/app/apps/worker/src
      - ./logs:/app/apps/worker/logs
    working_dir: /app/apps/worker
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/worker/src
          target: /app/apps/worker/src
        - action: rebuild
          path: ./apps/worker/package.json

  queue:
    container_name: scraper-queue-dev
    build:
      context: .
      dockerfile: ./apps/queue/Dockerfile
      target: dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./apps/queue/.env
    volumes:
      - ./apps/queue/src:/app/apps/queue/src
    working_dir: /app/apps/queue
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/queue/src
          target: /app/apps/queue/src
        - action: rebuild
          path: ./apps/queue/package.json

volumes:
  analytics_node_modules:
