name: Analytics CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/analytics/**'
      - '.github/workflows/deploy-analytics.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate Dockerfile
      run: docker build --target build apps/analytics/Dockerfile .
