name: Deploy All Apps

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      analytics-changed: ${{ steps.changes.outputs.analytics }}
      queue-changed: ${{ steps.changes.outputs.queue }}
      worker-changed: ${{ steps.changes.outputs.worker }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          analytics:
            - 'apps/analytics/**'
          queue:
            - 'apps/queue/**'
          worker:
            - 'apps/worker/**'

  deploy-analytics:
    needs: detect-changes
    if: needs.detect-changes.outputs.analytics-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Analytics Docker Build
      run: |
        docker build --target build -f apps/analytics/Dockerfile .
        
    - name: Deploy Analytics to Render
      run: |
        curl -X POST ${{ secrets.RENDER_ANALYTICS_DEPLOY_HOOK }}

  deploy-queue:
    needs: detect-changes
    if: needs.detect-changes.outputs.queue-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Queue Docker Build
      run: |
        docker build --target build --build-arg REPO_TOKEN=${{ secrets.REPO_TOKEN }} -f apps/queue/Dockerfile .
        
    - name: Deploy Queue to Render
      run: |
        curl -X POST ${{ secrets.RENDER_QUEUE_DEPLOY_HOOK }}
  
  deploy-worker:
    needs: detect-changes
    if: needs.detect-changes.outputs.worker-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Queue Docker Build
      run: |
        docker build --target build --build-arg REPO_TOKEN=${{ secrets.REPO_TOKEN }} -f apps/worker/Dockerfile .
        
    - name: Deploy Queue to Render
      run: |
        curl -X POST ${{ secrets.RENDER_WORKER_DEPLOY_HOOK }}
