name: Deploy All Apps

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.analytics == 'true' || steps.changes.outputs.backend == 'true' }}
      analytics-changed: ${{ steps.changes.outputs.analytics }}
      backend-changed: ${{ steps.changes.outputs.backend }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          analytics:
            - 'analytics/**'
          backend:
            - 'backend/**'

  deploy-analytics:
    needs: detect-changes
    if: needs.detect-changes.outputs.analytics-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Analytics Docker Build
      run: |
        docker build --target build -f analytics/Dockerfile .
        
    - name: Deploy Analytics to Render
      run: |
        curl -X POST ${{ secrets.RENDER_ANALYTICS_DEPLOY_HOOK }}

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Backend Docker Build
      run: |
        docker build --target build --build-arg REPO_TOKEN=${{ secrets.REPO_TOKEN }} -f backend/Dockerfile .
        
    - name: Deploy Backend to Render
      run: |
        curl -X POST ${{ secrets.RENDER_QUEUE_DEPLOY_HOOK }}
