name: Queue CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/queue/**'
      - '.github/workflows/deploy-queue.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate Dockerfile
      working-directory: ./apps/queue
      run: docker build --target build .
