name: Publish Packages to GitHub Packages

on:
  push:
    branches: [ main ]
    paths: 
      - 'packages/**'
      - '.github/workflows/publish-packages.yml'
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish all packages'
        required: false
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@iakhator'

      - name: Install and build packages
        run: |
          # Install and build types package (no dependencies)
          cd packages/types
          npm install
          npm run build
          cd ../..
          
          # Install and build logger package
          cd packages/logger
          npm install
          npm run build
          cd ../..
          
          # Install and build aws-wrapper package
          cd packages/aws-wrapper
          npm install
          npm run build
          cd ../..
          
          # Install and build core package (depends on other packages)
          cd packages/core
          npm install
          npm run build
          cd ../..

      - name: Publish @iakhator/scraper-types
        run: |
          cd packages/types
          npm publish || echo "Package may already exist or publish failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @iakhator/scraper-logger
        run: |
          cd packages/logger
          npm publish || echo "Package may already exist or publish failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @iakhator/scraper-aws-wrapper
        run: |
          cd packages/aws-wrapper
          npm publish || echo "Package may already exist or publish failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @iakhator/scraper-core
        run: |
          cd packages/core
          npm publish || echo "Package may already exist or publish failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
